spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/medimetrix_db
    username: postgres
    password: Free2sign@
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: medimetrix, public
    default-schema: medimetrix
    locations: classpath:db/migration

  thymeleaf:
    cache: false

server:
  port: 8080
