-- ============================================================
-- V15__add_fks_meta_part_unidade_especialidade.sql
-- Adiciona FKs pendentes em META e PARTICIPACAO (snapshots)
-- ============================================================

SET SEARCH_PATH TO MEDIMETRIX, public;

-- META → UNIDADE
ALTER TABLE MEDIMETRIX.META
    ADD CONSTRAINT FK_META_UNIDADE
        FOREIGN KEY (ID_UNIDADE)
            REFERENCES MEDIMETRIX.UNIDADE(ID_UNIDADE)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;

-- META → ESPECIALIDADE
ALTER TABLE MEDIMETRIX.META
    ADD CONSTRAINT FK_META_ESPECIALIDADE
        FOREIGN KEY (ID_ESPECIALIDADE)
            REFERENCES MEDIMETRIX.ESPECIALIDADE(ID_ESPECIALIDADE)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;

-- PARTICIPACAO (snapshots)
ALTER TABLE MEDIMETRIX.PARTICIPACAO
    ADD CONSTRAINT FK_PART_UNIDADE_SNAP
        FOREIGN KEY (UNIDADE_SNAPSHOT_ID)
            REFERENCES MEDIMETRIX.UNIDADE(ID_UNIDADE)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;

ALTER TABLE MEDIMETRIX.PARTICIPACAO
    ADD CONSTRAINT FK_PART_ESPEC_SNAP
        FOREIGN KEY (ESPECIALIDADE_SNAPSHOT_ID)
            REFERENCES MEDIMETRIX.ESPECIALIDADE(ID_ESPECIALIDADE)
            ON UPDATE RESTRICT
            ON DELETE RESTRICT;
