-- Auto-generated seed for 'Especialidade' → ESPECIALIDADE
-- Version V17
SET SEARCH_PATH TO MEDIMETRIX, public;

INSERT INTO MEDIMETRIX.ESPECIALIDADE (ID_ESPECIALIDADE, NOME, ATIVO) VALUES
  (1, 'Acupuntura', FALSE),
  (2, 'Alergia e Imunologia', TRUE),
  (3, 'Anestesiologia', TRUE),
  (4, 'Angiologia', TRUE),
  (5, 'Cardiologia', TRUE),
  (6, 'Cirurgia Cardiovascular', TRUE),
  (7, 'Cirurgia da Mão', TRUE),
  (8, 'Cirurgia de Cabeça e Pescoço', TRUE),
  (9, 'Cirurgia do Aparelho Digestivo', TRUE),
  (10, 'Cirurgia Geral', TRUE),
  (11, 'Cirurgia Oncológica', TRUE),
  (12, 'Cirurgia Pediátrica', TRUE),
  (13, 'Cirurgia Plástica', TRUE),
  (14, 'Cirurgia Torácica', TRUE),
  (15, 'Cirurgia Vascular', TRUE),
  (16, 'Clínica Médica', TRUE),
  (17, 'Coloproctologia', TRUE),
  (18, 'Dermatologia', TRUE),
  (19, 'Endocrinologia e Metabologia', TRUE),
  (20, 'Endoscopia', TRUE),
  (21, 'Gastroenterologia', TRUE),
  (22, 'Genética Médica', FALSE),
  (23, 'Geriatria', TRUE),
  (24, 'Ginecologia e Obstetrícia', TRUE),
  (25, 'Hematologia e Hemoterapia', TRUE),
  (26, 'Homeopatia', FALSE),
  (27, 'Infectologia', TRUE),
  (28, 'Mastologia', TRUE),
  (29, 'Medicina de Emergência', TRUE),
  (30, 'Medicina de Família e Comunidade', TRUE),
  (31, 'Medicina do Trabalho', FALSE),
  (32, 'Medicina do Tráfego', FALSE),
  (33, 'Medicina Esportiva', FALSE),
  (34, 'Medicina Física e Reabilitação', FALSE),
  (35, 'Medicina Intensiva', TRUE),
  (36, 'Medicina Legal e Perícia Médica', FALSE),
  (37, 'Medicina Nuclear', TRUE),
  (38, 'Medicina Preventiva e Social', FALSE),
  (39, 'Nefrologia', TRUE),
  (40, 'Neurocirurgia', TRUE),
  (41, 'Neurologia', TRUE),
  (42, 'Nutrologia', TRUE),
  (43, 'Oftalmologia', TRUE),
  (44, 'Oncologia Clínica', TRUE),
  (45, 'Ortopedia e Traumatologia', TRUE),
  (46, 'Otorrinolaringologia', TRUE),
  (47, 'Patologia', TRUE),
  (48, 'Patologia Clínica/Medicina Laboratorial', TRUE),
  (49, 'Pediatria', TRUE),
  (50, 'Pneumologia', TRUE),
  (51, 'Psiquiatria', TRUE),
  (52, 'Radiologia e Diagnóstico por Imagem', TRUE),
  (53, 'Radioterapia', TRUE),
  (54, 'Reumatologia', TRUE),
  (55, 'Urologia', TRUE);

-- Sync sequence for ESPECIALIDADE.ID_ESPECIALIDADE
SELECT setval(
               pg_get_serial_sequence('medimetrix.especialidade', 'id_especialidade'),
               COALESCE((SELECT MAX(id_especialidade) FROM medimetrix.especialidade), 0),
               true
       );
