-- Auto-generated seed for 'Questao' → QUESTAO
-- Version V22
SET SEARCH_PATH TO MEDIMETRIX, public;

INSERT INTO MEDIMETRIX.QUESTAO (ID_QUESTAO, ID_CRITERIO, ENUNCIADO, DESCRICAO_AUXILIAR, ATIVO, TIPO, OBRIGATORIEDADE, VALIDACAO_NUM_MIN, VALIDACAO_NUM_MAX, TAMANHO_TEXTO_MAX, SENSIVEL, VISIVEL_PARA_GESTOR, VERSAO, ORDEM_SUGERIDA) VALUES
  (1, 1, 'Confere a identificação do paciente antes de procedimentos.', 'Pulseira, nome completo e outro identificador.', TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (2, 1, 'Segue rotinas de dupla checagem para medicações de alto risco.', 'Insulina, anticoagulantes, eletrólitos concentrados.', TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (3, 1, 'Realiza time-out completo antes de procedimentos.', '1=Nunca; 2=Raro; 3=Parcial; 4=Quase sempre; 5=Sempre completo e documentado.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (4, 1, 'Reporta incidentes e quase-erros conforme protocolo institucional.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (5, 1, 'Registra alergias medicamentosas na primeira avaliação do paciente.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (6, 1, 'Higieniza as mãos nos 5 momentos preconizados (OMS).', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (7, 1, 'Comunica resultados críticos no prazo estabelecido.', '1=Atrasos frequentes; 2=Inconstante; 3=Prazo na maioria; 4=Tempestivo; 5=Tempestivo+documentado.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (8, 1, 'Confere lateralidade e sítio correto antes de procedimento.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (9, 1, 'Autoavaliação de domínio dos protocolos de segurança.', NULL, TRUE, 'NUM_0_10', 'OBRIGATORIA', 0, 10, NULL, FALSE, TRUE, 1, 9),
  (10, 1, 'Descreva uma melhoria de segurança que você implementou recentemente.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (11, 2, 'Aplica condutas baseadas em evidências atualizadas.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (12, 2, 'Realiza anamnese e exame físico completos e direcionados.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (13, 2, 'Indica exames complementares com critérios clínicos adequados.', '1=Não segue; 2=Parcial; 3=Segue com lembretes; 4=Segue autônomo; 5=Promove adesão.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (14, 2, 'Interpreta exames de forma correta e contextualizada.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (15, 2, 'Revisa interações medicamentosas antes de prescrever.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (16, 2, 'Reavalia resultados e ajusta conduta oportunamente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (17, 2, 'Apresenta domínio técnico compatível com sua especialidade.', '1=Fora da norma; 2=Oscila; 3=Conforme; 4=Conforme e atento; 5=Referência ética.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (18, 2, 'Documenta hipótese diagnóstica e diagnóstico diferencial.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (19, 2, 'Autoavaliação do próprio domínio técnico (0–10).', NULL, TRUE, 'NUM_0_10', 'OBRIGATORIA', 0, 10, NULL, FALSE, TRUE, 1, 9),
  (20, 2, 'Comente uma atualização científica que incorporou à prática neste período.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (21, 3, 'Explica diagnóstico e plano terapêutico de forma clara ao paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (22, 3, 'Utiliza linguagem acessível, adequada ao nível de compreensão do paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (23, 3, 'Favorece decisão compartilhada, verificando entendimento do paciente.', '1=Ausente; 2=Pouco clara; 3=Parcial; 4=Clara e completa; 5=Clara, completa e confirmada.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (24, 3, 'Mantém comunicação respeitosa com a equipe multiprofissional.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (25, 3, 'Entrega orientações por escrito quando indicado (ex.: alta).', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (26, 3, 'Demonstra escuta ativa durante consultas/atendimentos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (27, 3, 'Negocia plano terapêutico considerando preferências do paciente.', '1=Ausente; 2=Pouco clara; 3=Parcial; 4=Clara e completa; 5=Clara, completa e confirmada.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (28, 3, 'Comunica mudanças de conduta de forma tempestiva aos envolvidos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (29, 3, 'Informa riscos/benefícios de forma equilibrada.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (30, 3, 'Exemplo de comunicação difícil que você conduziu bem e o que aprendeu.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (31, 4, 'Cumpre horários e mantém pontualidade nas atividades.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (32, 4, 'Organiza a agenda para minimizar o tempo de espera do paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (33, 4, 'Mantém fluxo de atendimento eficiente sem perder qualidade.', '1=Atrasos; 2=Irregular; 3=Adequado; 4=Eficiente; 5=Ótimo com melhoria contínua.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (34, 4, 'Prioriza adequadamente casos urgentes e complexos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (35, 4, 'Atualiza pendências de prontuário até o final do dia.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (36, 4, 'Gerencia o tempo de consulta de forma adequada ao caso.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (37, 4, 'Adota rotinas que evitam retrabalho e desperdícios.', '1=Atrasos; 2=Irregular; 3=Adequado; 4=Eficiente; 5=Ótimo com melhoria contínua.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (38, 4, 'Cumpre prazos de devolutivas e pareceres.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (39, 4, 'Mantém checklist pessoal para tarefas recorrentes.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (40, 4, 'Cite uma melhoria de processo que você implementou para ganhar eficiência.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (41, 5, 'Segue diretrizes clínicas institucionais na maioria dos atendimentos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (42, 5, 'Atualiza-se quando houver revisão de protocolos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (43, 5, 'Aplica corretamente linhas de cuidado e caminhos clínicos.', '1=Não segue; 2=Parcial; 3=Segue com lembretes; 4=Segue autônomo; 5=Promove adesão.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (44, 5, 'Registra justificativa quando opta por conduta fora de protocolo.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (45, 5, 'Utiliza ferramentas de apoio à decisão clínica quando disponíveis.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (46, 5, 'Mantém prescrição em conformidade com listas e restrições da instituição.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (47, 5, 'Difunde boas práticas de adesão a protocolos na equipe.', '1=Não segue; 2=Parcial; 3=Segue com lembretes; 4=Segue autônomo; 5=Promove adesão.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (48, 5, 'Reporta inconformidades de protocolo quando identificadas.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (49, 5, 'Participa de auditorias/revisões de prontuário quando solicitado.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (50, 5, 'Sugira um ajuste de protocolo que poderia melhorar o cuidado.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (51, 6, 'Mantém confidencialidade das informações do paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (52, 6, 'Evita conflitos de interesse e comunica potenciais conflitos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (53, 6, 'Age com transparência e honestidade em situações adversas.', '1=Fora da norma; 2=Oscila; 3=Conforme; 4=Conforme e atento; 5=Referência ética.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (54, 6, 'Respeita limites de atuação e busca ajuda quando necessário.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (55, 6, 'Informa e registra eventos adversos de forma ética e tempestiva.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (56, 6, 'Trata pacientes e colegas com respeito, sem discriminação.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (57, 6, 'Cumpre normas e códigos de ética profissional.', '1=Fora da norma; 2=Oscila; 3=Conforme; 4=Conforme e atento; 5=Referência ética.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (58, 6, 'Zela pela integridade dos registros e documentos oficiais.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (59, 6, 'Cumpre regras de consentimento informado quando aplicável.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (60, 6, 'Descreva uma situação ética desafiadora e como você a conduziu.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (61, 7, 'Colabora ativamente com outros profissionais no cuidado do paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (62, 7, 'Respeita e integra contribuições de diferentes áreas.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (63, 7, 'Participa de reuniões clínicas de forma construtiva.', '1=Isolado; 2=Pouco cooperativo; 3=Coopera sob demanda; 4=Proativo; 5=Lidera colaboração.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (64, 7, 'Oferece e solicita ajuda quando necessário.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (65, 7, 'Registra comunicação com a equipe no prontuário quando relevante.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (66, 7, 'Fornece devolutivas claras e objetivas em contrarreferência.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (67, 7, 'Contribui para um ambiente de trabalho respeitoso e seguro.', '1=Isolado; 2=Pouco cooperativo; 3=Coopera sob demanda; 4=Proativo; 5=Lidera colaboração.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (68, 7, 'Acompanha planos interdisciplinares acordados.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (69, 7, 'Promove cultura de aprendizado com feedbacks respeitosos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (70, 7, 'Relate um caso em que a colaboração da equipe impactou o desfecho.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (71, 8, 'Demonstra empatia e acolhimento nas interações com o paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (72, 8, 'Respeita crenças, valores e preferências do paciente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (73, 8, 'Adapta a comunicação a vulnerabilidades e necessidades especiais.', '1=Frio; 2=Empatia limitada; 3=Empatia adequada; 4=Empatia consistente; 5=Altamente empático.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (74, 8, 'Garante privacidade e conforto durante atendimentos.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (75, 8, 'Oferece medidas de conforto e orientações de cuidado domiciliar quando indicadas.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (76, 8, 'Reconhece sinais de sofrimento emocional e encaminha adequadamente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (77, 8, 'Promove abordagem centrada na pessoa.', '1=Frio; 2=Empatia limitada; 3=Empatia adequada; 4=Empatia consistente; 5=Altamente empático.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (78, 8, 'Evita jargões e linguagem estigmatizante.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (79, 8, 'Inclui familiares/cuidadores quando apropriado e com consentimento.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 9),
  (80, 8, 'Descreva uma atitude de humanização que você considera essencial.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (81, 9, 'Registra informações clínicas de forma completa e tempestiva.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (82, 9, 'Utiliza corretamente campos estruturados e codificações.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (83, 9, 'Elabora sumários/contrarreferências claros e úteis.', '1=Incompleto; 2=Parcial; 3=Adequado; 4=Completo; 5=Completo e tempestivo.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (84, 9, 'Consulta e atualiza alergias/alertas ativos no sistema.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (85, 9, 'Anexa documentos e exames relevantes ao prontuário quando disponíveis.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (86, 9, 'Evita duplicidade de registros e corrige inconsistências.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (87, 9, 'Usa listas de problemas/medicações de forma atualizada.', '1=Incompleto; 2=Parcial; 3=Adequado; 4=Completo; 5=Completo e tempestivo.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (88, 9, 'Respeita regras de acesso e sigilo das informações.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (89, 9, 'Autoavaliação de proficiência no uso do prontuário eletrônico.', NULL, TRUE, 'NUM_0_10', 'OBRIGATORIA', 0, 10, NULL, FALSE, TRUE, 1, 9),
  (90, 9, 'Sugira uma melhoria no sistema de registro que impactaria sua prática.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10),
  (91, 10, 'Participa de atividades de educação continuada regularmente.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 1),
  (92, 10, 'Aplica aprendizados recentes na prática clínica.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 2),
  (93, 10, 'Compartilha conhecimento com a equipe (aulas, discussões de caso).', '1=Resistente; 2=Tardio; 3=Adota quando treinado; 4=Propaga boas práticas; 5=Propõe e mede impacto.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 3),
  (94, 10, 'Adota tecnologias e práticas inovadoras quando apropriado.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 4),
  (95, 10, 'Mantém portfólio/currículo atualizado com atividades formativas.', NULL, TRUE, 'CHECK', 'OBRIGATORIA', NULL, NULL, NULL, FALSE, TRUE, 1, 5),
  (96, 10, 'Busca feedback para aprimoramento contínuo.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 6),
  (97, 10, 'Propõe melhorias baseadas em dados e mede resultados.', '1=Resistente; 2=Tardio; 3=Adota quando treinado; 4=Propaga boas práticas; 5=Propõe e mede impacto.', TRUE, 'BARS_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 7),
  (98, 10, 'Participa de auditorias/PIQ/qualidade quando convocado.', NULL, TRUE, 'LIKERT_5', 'OBRIGATORIA', 1, 5, NULL, FALSE, TRUE, 1, 8),
  (99, 10, 'Autoavaliação de engajamento em educação e inovação.', NULL, TRUE, 'NUM_0_10', 'OBRIGATORIA', 0, 10, NULL, FALSE, TRUE, 1, 9),
  (100, 10, 'Relate uma inovação que você testou e o resultado observado.', NULL, TRUE, 'OPEN', 'OPCIONAL', NULL, NULL, 1000, FALSE, TRUE, 1, 10);

-- Sync sequence for QUESTAO.ID_QUESTAO
SELECT setval(
               pg_get_serial_sequence('medimetrix.questao', 'id_questao'),
               COALESCE((SELECT MAX(id_questao) FROM medimetrix.questao), 0),
               true
       );

