ALTER TABLE MEDIMETRIX.AVALIACAO
    ADD COLUMN ESCOPO VARCHAR(20) NOT NULL DEFAULT 'GLOBAL',
    ADD COLUMN ID_UNIDADE BIGINT NULL,
    ADD COLUMN ID_ESPECIALIDADE BIGINT NULL;

ALTER TABLE MEDIMETRIX.AVALIACAO
    ADD CONSTRAINT FK_AVALIACAO_UNIDADE
        FOREIGN KEY (ID_UNIDADE)
            REFERENCES MEDIMETRIX.UNIDADE (ID_UNIDADE);

ALTER TABLE MEDIMETRIX.AVALIACAO
    ADD CONSTRAINT FK_AVALIACAO_ESPECIALIDADE
        FOREIGN KEY (ID_ESPECIALIDADE)
            REFERENCES MEDIMETRIX.ESPECIALIDADE (ID_ESPECIALIDADE);
